# main.py
# The FastAPI application — this is what you RUN to start the server.
#
# To start the server:
#   uvicorn main:app --reload --port 8000
#
# Once running, visit:
#   http://localhost:8000/docs   ← Interactive API docs (auto-generated by FastAPI!)
#   http://localhost:8000        ← Health check

import uuid
from fastapi import FastAPI, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from typing import Optional

from models import ThreatEvent, SiteRegistration
from scorer import score_threat
from database import (
    init_db,
    register_site,
    get_site,
    save_incident,
    get_incidents,
    get_incident_stats
)
from alerter import send_alert
from config import settings

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="PhalanxAI Backend",
    description="Real-time website threat detection and alerting API",
    version="1.0.0"
)

# CORS = Cross-Origin Resource Sharing
# This allows your agent.js (running on ANY website) to POST to this backend.
# Without this, browsers block cross-origin requests for security.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # In production: replace with specific domains
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialise the database tables when the server starts
@app.on_event("startup")
def startup():
    init_db()
    print("🛡️  PhalanxAI backend is running")


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/")
def health_check():
    """Basic health check — confirms the server is alive."""
    return {"status": "ok", "service": "PhalanxAI", "version": "1.0.0"}


# ---------------------------------------------------------------------------
# Serve agent.js
# ---------------------------------------------------------------------------

@app.get("/agent.js")
def serve_agent():
    """
    Serves the browser security agent script.
    This is the file website owners embed in their HTML.
    """
    return FileResponse(
        path="agent.js",
        media_type="application/javascript",
        filename="agent.js"
    )


# ---------------------------------------------------------------------------
# Site registration
# ---------------------------------------------------------------------------

@app.post("/register")
def register_new_site(data: SiteRegistration):
    """
    Register a website with PhalanxAI.
    Returns a unique site_key that gets embedded in agent.js.

    Example request body:
    {
        "domain": "mystore.com",
        "admin_email": "admin@mystore.com",
        "site_name": "My Online Store"
    }
    """
    # Generate a unique key for this site
    site_key = f"phx_{uuid.uuid4().hex[:16]}"

    success = register_site(
        site_key=site_key,
        domain=data.domain,
        site_name=data.site_name,
        admin_email=data.admin_email
    )

    if not success:
        raise HTTPException(
            status_code=400,
            detail="Registration failed — domain may already be registered."
        )

    return {
        "site_key": site_key,
        "message": f"Site '{data.site_name}' registered successfully.",
        "script_tag": f'<script src="http://localhost:8000/agent.js" data-key="{site_key}" defer></script>',
        "instructions": "Add the script_tag above to your website's <head> or before </body>."
    }


# ---------------------------------------------------------------------------
# Main threat ingestion endpoint — agent.js posts here
# ---------------------------------------------------------------------------

@app.post("/threat")
async def receive_threat(
    event: ThreatEvent,
    x_internal_secret: Optional[str] = Header(default=None)
):
    """
    Core endpoint. Called by agent.js whenever it detects a threat.

    Pipeline:
      1. Verify internal secret
      2. Validate the site_key
      3. Score the threat
      4. Save to database
      5. Send email alert
      6. Return scoring result
    """

    # Step 0 — Verify request came from your agent.js
    if x_internal_secret != settings.INTERNAL_SECRET:
        raise HTTPException(status_code=403, detail="Forbidden.")

    # Step 1 — Validate the site key
    site = get_site(event.site_key)
    if not site:
        # Don't reveal whether the key exists or not — just reject silently
        raise HTTPException(status_code=401, detail="Invalid site key.")

    # Safety — trim oversized payloads before scoring/saving
    max_payload_length = getattr(settings, "MAX_PAYLOAD_LENGTH", 1000)
    if event.payload and len(event.payload) > max_payload_length:
        event.payload = event.payload[:max_payload_length]

    # Step 2 — Score the threat using the rule engine
    result = score_threat(event.threat_type, event.payload)

    # Step 3 — Save to database
    incident_id = save_incident(
        site_key=event.site_key,
        threat_type=event.threat_type,
        severity=result.severity,
        severity_score=result.score,
        payload=event.payload,
        url=event.url,
        visitor_ip=event.visitor_ip,
        explanation=result.explanation,
        recommendation=result.recommendation,
        blocked=result.blocked
    )

    # Step 4 — Send email alert (only for medium severity and above)
    alert_sent = False
    if result.severity in ("critical", "high", "medium"):
        alert_sent = send_alert(
            admin_email=site["admin_email"],
            site_name=site["site_name"],
            site_domain=site["domain"],
            threat_type=event.threat_type,
            severity=result.severity,
            score=result.score,
            url=event.url,
            explanation=result.explanation,
            recommendation=result.recommendation,
            blocked=result.blocked,
            incident_id=incident_id
        )

    # Step 5 — Return the scoring result to agent.js
    # agent.js uses the "blocked" flag to decide whether to halt the request
    return {
        "incident_id": incident_id,
        "severity": result.severity,
        "score": result.score,
        "blocked": result.blocked,
        "explanation": result.explanation,
        "alert_sent": alert_sent
    }


# ---------------------------------------------------------------------------
# Dashboard data endpoints
# ---------------------------------------------------------------------------

@app.get("/dashboard/{site_key}")
def get_dashboard_data(site_key: str):
    """
    Returns all incidents + stats for a site's dashboard.
    The React dashboard calls this endpoint on load and polls it.
    """
    site = get_site(site_key)
    if not site:
        raise HTTPException(status_code=404, detail="Site not found.")

    incidents = get_incidents(site_key, limit=100)
    stats = get_incident_stats(site_key)

    return {
        "site": {
            "name": site["site_name"],
            "domain": site["domain"],
        },
        "stats": stats,
        "incidents": incidents
    }


@app.get("/incidents/{site_key}")
def list_incidents(site_key: str, limit: int = 50):
    """
    Returns recent incidents for a site. Used for real-time polling by the dashboard.
    """
    site = get_site(site_key)
    if not site:
        raise HTTPException(status_code=404, detail="Site not found.")

    limit = max(1, min(limit, 200))  # Prevent abuse / huge queries
    return {"incidents": get_incidents(site_key, limit=limit)}


# ---------------------------------------------------------------------------
# Dev/demo helper — simulate a threat without agent.js
# ---------------------------------------------------------------------------

@app.post("/demo/simulate")
async def simulate_threat(
    site_key: str,
    threat_type: str = "xss_attempt",
    payload: str = "<script>document.cookie</script>",
    url: str = "https://demo-site.com/contact"
):
    """
    Injects a fake threat event for demo/testing purposes.
    Use this during the hackathon to trigger alerts without a real attack.

    Example:
      POST /demo/simulate?site_key=phx_abc123&threat_type=sql_injection
    """
    fake_event = ThreatEvent(
        site_key=site_key,
        threat_type=threat_type,
        payload=payload,
        url=url,
        visitor_ip="203.0.113.42",   # RFC 5737 documentation IP — safe to use in demos
        user_agent="Demo/1.0",
        timestamp=None
    )

    # Reuse the main threat handler directly
    return await receive_threat(fake_event, x_internal_secret=settings.INTERNAL_SECRET)